// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.sister.statportal.odata.domain;

import java.io.Serializable;

privileged aspect MdRelHierNodePK_Roo_Serializable {
    
    declare parents: MdRelHierNodePK implements Serializable;
    
    private static final long MdRelHierNodePK.serialVersionUID = 1L;
    
}
